package agent

import (
	"github.com/hashicorp/hcl-lang/lang"
	"github.com/hashicorp/hcl-lang/schema"
	schemautils "github.com/loczek/nomad-ls/internal/schemaUtils"
	"github.com/zclconf/go-cty/cty"
)

var ServerSchema = &schema.BodySchema{
	Attributes: map[string]*schema.AttributeSchema{
		"authoritative_region": {
			Description:  lang.Markdown("Specifies the authoritative region, which provides a single source of truth for global configurations such as ACL Policies and global ACL tokens in multi-region, federated deployments. Non-authoritative regions will replicate from the authoritative to act as a mirror. By default, the local region is assumed to be authoritative. Setting authoritative_region assumes that ACLs have been bootstrapped in the authoritative region. Refer to Configure for multiple regions in the ACLs tutorial."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"bootstrap_expect": {
			Description: lang.Markdown("Specifies the number of server nodes to wait for before bootstrapping. It is most common to use the odd-numbered integers 3 or 5 for this value, depending on the cluster size. A value of 1 does not provide any fault tolerance and is not recommended for production use cases."),
			Constraint:  schema.LiteralType{Type: cty.Number},
			IsRequired:  true,
		},
		"data_dir": {
			Description:  lang.Markdown("Specifies the directory to use for server-specific data, including the replicated log. When this parameter is empty, Nomad will generate the path using the top-level data_dir suffixed with server, like \"/opt/nomad/server\". The top-level data_dir must be set, even when setting this value. This must be an absolute path. Nomad will create the directory on the host, if it does not exist when the agent process starts."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"enabled": {
			Description:  lang.Markdown("Specifies if this agent should run in server mode. All other server options depend on this value being set."),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(false)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
		},
		"enabled_schedulers": {
			Description:  lang.Markdown("Specifies which sub-schedulers this server handles. Use this to restrict the evaluations that worker threads dequeue for processing. Nomad treats the empty default value as [\"service\", \"batch\", \"system\", \"sysbatch\"]."),
			DefaultValue: schema.DefaultValue{Value: cty.ListValEmpty(cty.String)},
			Constraint:   schema.LiteralType{Type: cty.List(cty.String)},
			IsOptional:   true,
		},
		"enable_event_broker": {
			Description:  lang.Markdown("Specifies if this server will generate events for its event stream."),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(true)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
		},
		"encrypt": {
			Description:  lang.Markdown("Specifies the secret key to use for encryption of Nomad server's gossip network traffic. This key must be 32 bytes that are RFC4648 \"URL and filename safe\" base64-encoded. You can generate an appropriately-formatted key with the nomad operator gossip keyring generate command. The provided key is automatically persisted to the data directory and loaded automatically whenever the agent is restarted. This means that to encrypt Nomad server's gossip protocol, this option only needs to be provided once on each agent's initial startup sequence. If it is provided after Nomad has been initialized with an encryption key, then the provided key is ignored and a warning will be displayed. Refer to the encryption documentation for more details on this option and its impact on the cluster."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"event_buffer_size": {
			Description:  lang.Markdown("Specifies the number of events generated by the server to be held in memory. Increasing this value enables new subscribers to have a larger look back window when initially subscribing. Decreasing will lower the amount of memory used for the event buffer."),
			DefaultValue: schema.DefaultValue{Value: cty.NumberIntVal(100)},
			Constraint:   schema.LiteralType{Type: cty.Number},
			IsOptional:   true,
		},
		"node_gc_threshold": {
			Description:  lang.Markdown("Specifies how long a node must be in a terminal state before it is garbage collected and purged from the system. This is specified using a label suffix like \"30s\" or \"1h\"."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("24h")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"job_gc_interval": {
			Description:  lang.Markdown("Specifies the interval between the job garbage collections. Only jobs who have been terminal for at least job_gc_threshold will be collected. Lowering the interval will perform more frequent but smaller collections. Raising the interval will perform collections less frequently but collect more jobs at a time. Reducing this interval is useful if there is a large throughput of tasks, leading to a large set of dead jobs. This is specified using a label suffix like \"30s\" or \"3m\"."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("5m")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"job_gc_threshold": {
			Description:  lang.Markdown("Specifies the minimum time a job must be in the terminal state before it is eligible for garbage collection. This is specified using a label suffix like \"30s\" or \"1h\"."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("4h")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"eval_gc_threshold": {
			Description:  lang.Markdown("Specifies the minimum time an evaluation must be in the terminal state before it is eligible for garbage collection. This is specified using a label suffix like \"30s\" or \"1h\". Note that batch job evaluations are controlled via batch_eval_gc_threshold. Nomad garbage collects allocations with their evaluations, so this field also controls server garbage collection of allocations. Evaluations with non-terminal allocations cannot be garbage collected."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("1h")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"batch_eval_gc_threshold": {
			Description:  lang.Markdown("Specifies the minimum time an evaluation stemming from a batch job must be in the terminal state before it is eligible for garbage collection. This is specified using a label suffix like \"30s\" or \"1h\". Note that the threshold is a necessary but insufficient condition for collection, and the most recent evaluation won't be garbage collected even if it breaches the threshold. Allocations are garbage collected with their evaluations, so this field also controls server garbage collection of allocations. Evaluations with non-terminal allocations cannot be garbage collected."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("24h")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"deployment_gc_threshold": {
			Description:  lang.Markdown("Specifies the minimum time a deployment must be in the terminal state before it is eligible for garbage collection. This is specified using a label suffix like \"30s\" or \"1h\"."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("1h")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"csi_volume_claim_gc_interval": {
			Description:  lang.Markdown("Specifies the interval between CSI volume claim garbage collections."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("5m")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"csi_volume_claim_gc_threshold": {
			Description:  lang.Markdown("Specifies the minimum age of a CSI volume before it is eligible to have its claims garbage collected. This is specified using a label suffix like \"30s\" or \"1h\"."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("1h")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"csi_plugin_gc_threshold": {
			Description:  lang.Markdown("Specifies the minimum age of a CSI plugin before it is eligible for garbage collection if not in use. This is specified using a label suffix like \"30s\" or \"1h\"."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("1h")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"acl_token_gc_threshold": {
			Description:  lang.Markdown("Specifies the minimum age of an expired ACL token before it is eligible for garbage collection. This is specified using a label suffix like \"30s\" or \"1h\"."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("1h")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"heartbeat_grace": {
			Description:  lang.Markdown("Specifies the additional time given beyond the heartbeat TTL of Clients to account for network and processing delays and clock skew. This is specified using a label suffix like \"30s\" or \"1h\". Refer to the Client Heartbeats section for details."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("10s")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"min_heartbeat_ttl": {
			Description:  lang.Markdown("Specifies the minimum time between Client heartbeats. This is used as a floor to prevent excessive updates. This is specified using a label suffix like \"30s\" or \"1h\". Refer to the Client Heartbeats section for details."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("10s")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"failover_heartbeat_ttl": {
			Description:  lang.Markdown("The time by which all Clients must heartbeat after a Server leader election. This is specified using a label suffix like \"30s\" or \"1h\". Refer to the Client Heartbeats section for details."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("5m")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"max_heartbeats_per_second": {
			Description:  lang.Markdown("Specifies the maximum target rate of heartbeats being processed per second. This allows the TTL to be increased to meet the target rate. Refer to the Client Heartbeats section for details."),
			DefaultValue: schema.DefaultValue{Value: cty.NumberFloatVal(50.0)},
			Constraint:   schema.LiteralType{Type: cty.Number},
			IsOptional:   true,
		},
		"non_production": {
			Description:  lang.Markdown("Specifies that this cluster is a non-production deployment. When set, this flag is passed to license instantiation and usage reporting. Requires a valid non-production license. This configuration option is not Enterprise-only. However, setting this flag only affects Enterprise functionality."),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(false)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
		},
		"non_voting_server": {
			Description:  lang.Markdown("Specifies whether this server will act as a non-voting member of the cluster to help provide read scalability." + schemautils.Divider + schemautils.EnterpriseOnly),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(false)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
		},
		"num_schedulers": {
			Description: lang.Markdown("Specifies the number of parallel scheduler threads to run. This can be as many as one per core, or 0 to disallow this server from making any scheduling decisions. This defaults to the number of CPU cores."),
			Constraint:  schema.LiteralType{Type: cty.Number},
			IsOptional:  true,
		},
		"license_path": {
			Description:  lang.Markdown("Specifies the path to load a Nomad Enterprise license from. This must be an absolute path (ex. /etc/nomad.d/license.hclic). The license can also be set by setting NOMAD_LICENSE_PATH or by setting NOMAD_LICENSE as the entire license value. license_path has the highest precedence, followed by NOMAD_LICENSE and then NOMAD_LICENSE_PATH. This configuration also applies to Nomad licenses obtained through IBM Passport Advantage Online (PAO)."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"disable_log_cache": {
			Description:  lang.Markdown("Disables the in-memory cache for recent Raft logs. Disabling the cache may reduce memory usage but will increase disk reads for log operations."),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(false)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
		},
		"raft_protocol": {
			Description:  lang.Markdown("Specifies the Raft protocol version to use when communicating with other Nomad servers. This affects available Autopilot features and is typically not required as the agent internally knows the latest version, but may be useful in some upgrade scenarios. Must be 3 in Nomad v1.4 or later."),
			DefaultValue: schema.DefaultValue{Value: cty.NumberIntVal(3)},
			Constraint:   schema.LiteralType{Type: cty.Number},
			IsOptional:   true,
		},
		"raft_multiplier": {
			Description:  lang.Markdown("An integer multiplier used by Nomad servers to scale key Raft timing parameters. Omitting this value or setting it to 0 uses default timing described in the following paragraph. Lower values are used to tighten timing and increase sensitivity while higher values relax timings and reduce sensitivity. Tuning this affects the time it takes Nomad to detect leader failures and to perform leader elections, at the expense of requiring more network and CPU resources for better performance. The maximum allowed value is 10. By default, Nomad will use the highest-performance timing, currently equivalent to setting this to a value of 1. Increasing the timings makes leader election less likely during periods of networking issues or resource starvation. Since leader elections pause Nomad's normal work, it may be beneficial for slow or unreliable networks to wait longer before electing a new leader. The trade-off when raising this value is that during network partitions or other events (server crash) where a leader is lost, Nomad will not elect a new leader for a longer period of time than the default. The nomad.nomad.leader.barrier and nomad.raft.leader.lastContact metrics are a good indicator of how often leader elections occur and Raft latency."),
			DefaultValue: schema.DefaultValue{Value: cty.NumberIntVal(1)},
			Constraint:   schema.LiteralType{Type: cty.Number},
			IsOptional:   true,
		},
		"raft_snapshot_threshold": {
			Description:  lang.Markdown("Specifies the minimum number of Raft logs to be written to disk before the node is allowed to take a snapshot. This reduces the frequency and impact of creating snapshots. During node startup, Raft restores the latest snapshot and then applies the individual logs to catch the node up to the last known state. This can be tuned during operation by a hot configuration reload."),
			DefaultValue: schema.DefaultValue{Value: cty.NumberIntVal(8192)},
			Constraint:   schema.LiteralType{Type: cty.Number},
			IsOptional:   true,
		},
		"raft_snapshot_interval": {
			Description:  lang.Markdown("Specifies the minimum time between checks if Raft should perform a snapshot. The Raft library randomly staggers between this value and twice this value to avoid the entire cluster performing a snapshot at once. Nodes are eligible to snapshot once they have exceeded the raft_snapshot_threshold. This value can be tuned during operation by a hot configuration reload."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("120s")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"raft_trailing_logs": {
			Description:  lang.Markdown("Specifies how many logs are retained after a snapshot. These logs are used so that Raft can quickly replay logs on a follower instead of being forced to send an entire snapshot. This value can be tuned during operation by a hot configuration reload."),
			DefaultValue: schema.DefaultValue{Value: cty.NumberIntVal(10240)},
			Constraint:   schema.LiteralType{Type: cty.Number},
			IsOptional:   true,
		},
		"redundancy_zone": {
			Description:  lang.Markdown("Specifies the redundancy zone that this server will be a part of for Autopilot management. For more information, refer to the Autopilot Guide." + schemautils.Divider + schemautils.EnterpriseOnly),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"rejoin_after_leave": {
			Description:  lang.Markdown("Specifies if Nomad will ignore a previous leave and attempt to rejoin the cluster when starting. By default, Nomad treats leave as a permanent intent and does not attempt to join the cluster again when starting. This flag allows the previous state to be used to rejoin the cluster."),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(false)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
		},
		"root_key_gc_interval": {
			Description:  lang.Markdown("Specifies the interval between encryption key metadata garbage collections."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("10m")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"root_key_gc_threshold": {
			Description:  lang.Markdown("Specifies the minimum time after the root_key_rotation_threshold has passed that an encryption key must exist before it can be eligible for garbage collection."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("1h")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"root_key_rotation_threshold": {
			Description:  lang.Markdown("Specifies the lifetime of an active encryption key before it is automatically rotated on the next garbage collection interval. Nomad will prepublish the replacement key at half the root_key_rotation_threshold time so external consumers of Workload Identity have time to obtain the new public key from the JWKS URL before it is used."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("720h")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"start_timeout": {
			Description:  lang.Markdown("A timeout applied to the server setup and startup processes. These processes (keyring decryption) are expected to complete before the server is considered healthy, and if the timeout is reached before they are completed, the server will exit. Without this, the server can hang indefinitely waiting for these."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("30s")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"upgrade_version": {
			Description:  lang.Markdown("A custom version of the format X.Y.Z to use in place of the Nomad version when custom upgrades are enabled in Autopilot. For more information, refer to the [Autopilot Guide](https://developer.hashicorp.com/nomad/docs/manage/autopilot)."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"job_max_priority": {
			Description:  lang.Markdown("Specifies the maximum priority that can be assigned to a job. A valid value must be between 100 and 32766."),
			DefaultValue: schema.DefaultValue{Value: cty.NumberIntVal(100)},
			Constraint:   schema.LiteralType{Type: cty.Number},
			IsOptional:   true,
		},
		"job_default_priority": {
			Description:  lang.Markdown("Specifies the default priority assigned to a job. A valid value must be between 50 and job_max_priority."),
			DefaultValue: schema.DefaultValue{Value: cty.NumberIntVal(50)},
			Constraint:   schema.LiteralType{Type: cty.Number},
			IsOptional:   true,
		},
		"job_max_count": {
			Description:  lang.Markdown("Specifies the maximum number of allocations for a job, as represented by the sum of its task group count fields. Jobs of type system ignore this value. The child jobs of dispatched batch jobs or periodic jobs are counted separately from their parent job. This value must be non-negative. If set to 0, no limit is enforced. This value is enforced at the time the job is submitted or scaled, and updating the value will not impact existing jobs."),
			DefaultValue: schema.DefaultValue{Value: cty.NumberIntVal(50000)},
			Constraint:   schema.LiteralType{Type: cty.Number},
			IsOptional:   true,
		},
		"job_max_source_size": {
			Description:  lang.Markdown("Specifies the size limit of the associated job source content when registering a job. Note this is not a limit on the actual size of a job. If the limit is exceeded, the original source is simply discarded and no error is returned from the job API."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("1M")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"job_tracked_versions": {
			Description:  lang.Markdown("Specifies the number of historic job versions that are kept."),
			DefaultValue: schema.DefaultValue{Value: cty.NumberIntVal(6)},
			Constraint:   schema.LiteralType{Type: cty.Number},
			IsOptional:   true,
		},
		"oidc_issuer": {
			Description:  lang.Markdown("Specifies the Issuer URL for Workload Identity JWTs. For example, \"https://nomad.example.com\". If set the /.well-known/openid-configuration HTTP endpoint is enabled for third parties to discover Nomad's OIDC configuration. Once set oidc_issuer cannot be changed without invalidating Workload Identities that have the old issuer claim. For this reason it is suggested to set oidc_issuer to a proxy in front of Nomad's HTTP API to ensure a stable DNS name can be used instead of a potentially ephemeral Nomad server IP."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
	},
	Blocks: map[string]*schema.BlockSchema{
		"client_introduction": {
			Description: lang.Markdown("Configuration for how the Nomad server handles client introduction requests."),
			Body:        ClientIntroductionSchema,
		},
		"default_scheduler_config": {
			Description: lang.Markdown("Specifies the initial default scheduler config when bootstrapping cluster. The parameter is ignored once the cluster is bootstrapped or value is updated through the [API endpoint](https://developer.hashicorp.com/nomad/api-docs/operator/scheduler#update-scheduler-configuration). Refer to [the example section](https://developer.hashicorp.com/nomad/docs/configuration/server#configuring-scheduler-config) for more details."),
			Body:        DefaultSchedulerConfigSchema,
		},
		"plan_rejection_tracker": {
			Description: lang.Markdown("Configuration for the plan rejection tracker that the Nomad leader uses to track the history of plan rejections."),
			Body:        PlanRejectionTrackerSchema,
		},
		"raft_boltdb": {
			Description:  lang.Markdown("This is a nested object that allows configuring options for Raft's BoltDB based log store."),
			Body:         RaftBoltDBSchema,
			IsDeprecated: true,
		},
		"raft_logstore": {
			Description: lang.Markdown("This is a nested object that allows configuring options for Raft's log store backend. This replaces the deprecated raft_boltdb configuration."),
			Body:        RaftLogstoreSchema,
		},
		"verification": {
			Description: lang.Markdown("Configuration options for Raft log store verification (debugging feature)."),
			Body:        VerificationSchema,
		},
		"server_join": {
			Description: lang.Markdown("Specifies how the Nomad server will connect to other Nomad servers. The `retry_join` fields may directly specify the server address or use go-discover syntax for auto-discovery. Refer to the [server_join documentation](https://developer.hashicorp.com/nomad/docs/configuration/server_join) for more detail."),
			Body:        ServerJoinSchema,
		},
		"search": {
			Description: lang.Markdown("Specifies configuration parameters for the Nomad search API."),
			Body:        SearchSchema,
		},
	},
}

var RaftLogstoreSchema = &schema.BodySchema{
	Attributes: map[string]*schema.AttributeSchema{
		// TODO: this should be a dep key for boltdb and wal blocks
		"backend": {
			Description:  lang.Markdown("Specifies which Raft log store backend to use. Valid values are \"boltdb\" (default) or \"wal\" (experimental). The wal backend uses the HashiCorp Raft WAL log store which can provide better performance characteristics for write-heavy workloads. Once a backend is selected and the server is started, changing to a different backend requires migration using the nomad operator raft migrate-backend command."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("boltdb")},
			Constraint: schema.OneOf{
				schema.LiteralValue{Value: cty.StringVal("boltdb")},
				schema.LiteralValue{Value: cty.StringVal("wal")},
			},
			IsOptional: true,
			IsDepKey:   true,
		},
	},
	Blocks: map[string]*schema.BlockSchema{
		"boltdb": {
			Body: BoltDBSchema,
		},
		"wal": {
			Body: WalSchema,
		},
	},
}

var BoltDBSchema = &schema.BodySchema{
	Attributes: map[string]*schema.AttributeSchema{
		"no_freelist_sync": {
			Description:  lang.Markdown("Setting this to `true` will disable syncing the BoltDB freelist to disk within the `raft.db` file. Not syncing the freelist to disk will reduce disk IO required for write operations at the expense of potentially increasing server startup times."),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(false)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
		},
	},
}

var WalSchema = &schema.BodySchema{
	Attributes: map[string]*schema.AttributeSchema{
		"segment_size_mb": {
			Description:  lang.Markdown("Specifies the size in megabytes of each WAL segment file. The default is 64MB. Larger segment sizes may improve performance for write-heavy workloads but will increase the minimum disk space required."),
			DefaultValue: schema.DefaultValue{Value: cty.NumberIntVal(64)},
			Constraint:   schema.LiteralType{Type: cty.Number},
			IsOptional:   true,
		},
	},
}

var VerificationSchema = &schema.BodySchema{
	Attributes: map[string]*schema.AttributeSchema{
		"enabled": {
			Description:  lang.Markdown("Enables detailed verification logging of the Raft log store for debugging purposes. When enabled, the server will emit debug-level logs with detailed Raft-related information for both BoltDB and WAL backends. This is intended for troubleshooting and should not be enabled in production environments unless actively debugging Raft issues."),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(false)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
		},
		"interval": {
			Description:  lang.Markdown("Specifies the interval at which verification checks are performed when verification is enabled. This is specified using a label suffix like \"30s\" or \"5m\"."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("5m")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
	},
}

var ClientIntroductionSchema = &schema.BodySchema{
	Attributes: map[string]*schema.AttributeSchema{
		"enforcement": {
			Description:  lang.Markdown("Specifics how the server handles new client registration requests. The valid options are none, warn, and strict."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("warn")},
			Constraint: schema.OneOf{
				schema.LiteralValue{Value: cty.StringVal("none")},
				schema.LiteralValue{Value: cty.StringVal("warn")},
				schema.LiteralValue{Value: cty.StringVal("strict")},
			},
			IsOptional: true,
		},
		"default_identity_ttl": {
			Description:  lang.Markdown("The default TTL assigned to generated client introduction tokens when the caller does not specify a TTL. Specify this value with a label suffix like \"30s\" or \"1h\". Must be less than `max_identity_ttl`."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("5m")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
		"max_identity_ttl": {
			Description:  lang.Markdown("The maximum TTL that can be requested by a caller when generating client introduction tokens. Specify this value with a label suffix like \"30s\" or \"1h\". Must be greater than `default_identity_ttl`."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("30m")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
	},
}

var PlanRejectionTrackerSchema = &schema.BodySchema{
	Attributes: map[string]*schema.AttributeSchema{
		"enabled": {
			Description:  lang.Markdown("Specifies if plan rejections should be tracked."),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(false)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
		},
		"node_threshold": {
			Description:  lang.Markdown("The number of plan rejections for a node within the node_window to trigger a client to be set as ineligible."),
			DefaultValue: schema.DefaultValue{Value: cty.NumberIntVal(100)},
			Constraint:   schema.LiteralType{Type: cty.Number},
			IsOptional:   true,
		},
		"node_window": {
			Description:  lang.Markdown("The time window for when plan rejections for a node should be considered."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("5m")},
			Constraint:   schema.LiteralType{Type: cty.String},
			IsOptional:   true,
		},
	},
}

var RaftBoltDBSchema = &schema.BodySchema{
	Attributes: map[string]*schema.AttributeSchema{
		"no_freelist_sync": {
			Description:  lang.Markdown("Setting this to true will disable syncing the BoltDB freelist to disk within the raft.db file. Not syncing the freelist to disk will reduce disk IO required for write operations at the expense of longer server startup times."),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(false)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
			IsDeprecated: true,
		},
	},
}

var DefaultSchedulerConfigSchema = &schema.BodySchema{
	Attributes: map[string]*schema.AttributeSchema{
		"scheduler_algorithm": {
			Description:  lang.Markdown("Specifies whether scheduler binpacks or spreads allocations on available nodes. Possible values are `\"binpack\"` and `\"spread\"`. This value may also be set per [node pool](https://developer.hashicorp.com/nomad/docs/other-specifications/node-pool#scheduler_algorithm)."),
			DefaultValue: schema.DefaultValue{Value: cty.StringVal("binpack")},
			Constraint: schema.OneOf{
				schema.LiteralValue{Value: cty.StringVal("binpack")},
				schema.LiteralValue{Value: cty.StringVal("spread")},
			},
			IsOptional: true,
		},
		"memory_oversubscription_enabled": {
			Description:  lang.Markdown("When `true`, tasks may exceed their reserved memory limit, if the client has excess memory capacity. Tasks must specify [`memory_max`](https://developer.hashicorp.com/nomad/docs/job-specification/resources#memory_max) to take advantage of memory oversubscription. This value may also be set per [node pool](https://developer.hashicorp.com/nomad/docs/other-specifications/node-pool#memory_oversubscription_enabled)."),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(false)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
		},
		"reject_job_registration": {
			Description:  lang.Markdown("When `true`, the server will return permission denied errors for job registration, job dispatch, and job scale APIs, unless the ACL token for the request is a management token. If ACLs are disabled, no user will be able to register jobs. This allows operators to shed load from automated processes during incident response."),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(false)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
		},
		"pause_eval_broker": {
			Description:  lang.Markdown("When set to `true`, the eval broker which usually runs on the leader will be disabled. This will prevent the scheduler workers from receiving new work."),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(false)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
		},
	},
	Blocks: map[string]*schema.BlockSchema{
		"preemption_config": {
			Description: lang.Markdown("Options to enable preemption for various schedulers."),
			Body:        PreemptionConfigSchema,
		},
	},
}

var PreemptionConfigSchema = &schema.BodySchema{
	Attributes: map[string]*schema.AttributeSchema{
		"system_scheduler_enabled": {
			Description:  lang.Markdown("Specifies whether preemption for system jobs is enabled. Note that if this is set to true, then system jobs can preempt any other jobs."),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(true)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
		},
		"sys_batch_scheduler_enabled": {
			Description:  lang.Markdown("Specifies whether preemption for system batch jobs is enabled. Note that if this is set to true, then system batch jobs can preempt any other jobs."),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(false)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
		},
		"batch_scheduler_enabled": {
			Description:  lang.Markdown("Specifies whether preemption for batch jobs is enabled. Note that if this is set to true, then batch jobs can preempt any other jobs."),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(false)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
		},
		"service_scheduler_enabled": {
			Description:  lang.Markdown("Specifies whether preemption for service jobs is enabled. Note that if this is set to true, then service jobs can preempt any other jobs."),
			DefaultValue: schema.DefaultValue{Value: cty.BoolVal(false)},
			Constraint:   schema.LiteralType{Type: cty.Bool},
			IsOptional:   true,
		},
	},
}
